name: PR Comment
on: issue_comment

jobs:     
  debug:
    runs-on: ubuntu-latest    
    steps:
    - name: see payload
      run: echo "$PAYLOAD"
      env:
        PAYLOAD: ${{ toJSON(github.event) }}
  comment:
    if: contains(github.event.comment.body, '/pablo-action')
    runs-on: ubuntu-latest  
    steps:
      - uses: actions/github-script@v3
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '👋 Thanks for reporting!'
            })
